language: php

php:
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
    - composer install --dev
    - bin/composer install --dev --prefer-source

script:
    - ./bin/phpunit
